name: Styling Spaces Sydney
favicon: null
layout_spectrum: 0.14065
typography_spectrum: 0.93806
title: Sydney Property Styling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfcbc4'
    - '#000000'
    - '#8d8d8d'
    - '#92563f'
    - '#002f00'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
