name: Styling Spaces Sydney
favicon: null
layout_spectrum: 0.82659
typography_spectrum: 0
title: Sydney Property Styling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f3f7'
    - '#272d39'
    - '#c1c2c7'
    - '#6b7281'
    - '#939eb1'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
