name: Styling Spaces Sydney
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Sydney Property Styling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cec4b5'
    - '#ffffff'
    - '#918a84'
    - '#49362e'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 1
purpose: []
